### ISSUE TITLE
Batch Updates for catalog product assortement

### ISSUE THREAD

**Issue by YSavitski** [meplato/store2-java-client#43]
Hi dear collegues,

we have Intergration with Meplato where our company manages 30+ active catalogs aand near 40mio products. 
We ahve a daily routine problem to provide updates like stock & price changes.

We're commonly have the saem situation that during 24h we need to update ~70% of our assortment. 
Right now Meplato APU doesn't provide any option to go with bulk updates, therefore we're sending update for each indifidual product. 

Rigth now we use 8 independent workers but still spend roughly 24h to send all necessary updates for all affected assortement.
From time to time we also may see timeouts and cetra...

Would it be possible to provide Bulk API for product updates at least? 

Thank you in advance for your feedback

**Comment by olivere** [comment]
Hello @YSavitski! We have skipped Bulk APIs for years because of observations and issues. They might not be important to you, but we have to consider everything before offering an option that would cause more harm afterward.

1. Technically, a Bulk API would be fine. However, there are quite a lot of suppliers who see their technical capabilities as an aftersight. If we establish a Bulk API, they will use it. And we would need to train them to get the semantics right. E.g. if you bulk update 10 products: Would an error with one of the products rollback all 10 updates? How would you return the errors and the successful items? You might not believe how many suppliers are out there blindly hammering our API and ignoring errors altogether, some of which use their homebrew REST API instead of the provided ones. We have to support all of them.
2. Offering a Bulk API moves the burden to our side. You probably keep your 8 workers, but we now receive—say—800 instead of 8 updates in the same amount of time. We would need to add capacity for that.
3. Observing the API calls, we see many suppliers updating everything, even if not necessary, because they can't track whether to update at all. Offering a Bulk API for those use cases would be the worst thing we could do.
4. Updating on a day-to-day basis is probably not necessary. We see many buyers still trying to manually approve changes to catalogs, and they end up simply approving your latest change. Notice: We could move to real-time (or at least near-real-time) updates, but most buyers still insist on _not_ doing that. Digitization at its best. So maybe it would make sense to discuss the update frequency on the business level first before trying to fix latency issues for nothing.
5. Remember: This API is still free for you, right? But someone has to pay for all of the support, maintenance and capacity provisioning.

Again, this is probably not the response you'd hoped for. But for now, we will not offer Bulk APIs.

**Comment by YSavitski** [comment]
Hey @olivere 
Thank you very much for your detailed answer, I really appreciate it, and keep my fingers crossed that I didn't bother you too much with my questions.

Now the picture is becoming clearer to me. I can't agree with all the points regarding Offering Bulk API, but at the same time I accept and respect your decision.

We will check our processes in respect of your suggestions and probably will reduce frequency or introduce more workers, because from the business perspecteve our Company would like to increse product assortment for our buyers. 
Let us see

Best regards
