### ISSUE TITLE
Base Class for Product?

### ISSUE THREAD

**Issue by manuelbostanci** [meplato/store2-java-client#5]
Hi @olivere,
Is there a reason why the classes UpdateProduct, CreateProduct, UpsertProduct, and Product contain all attributes and no inheritance hierarchy was implemented here?
On our side, this also leads to a lot of code duplication.
What do you think about implementing a base class (e.g. Product) from which the CreateProduct, UpdateProduct, UpsertProduct classes inherit.

Thanks for your efforts!

**Comment by olivere** [comment]
Hi @manuelbostanci,

there's some technical and some non-technical reasons to do so.

First, the API is generated by a code generator for every supported language/platform from an API specification much like Swagger/OpenAPI; although one can try to implement inheritance there, it's not straightforward and not simple to achieve. As such, the different endpoints are independent of each other and simply don't share any attributes or properties, although I agree 90% of them are the same.

Second, some endpoints have subtle differences. E.g. while in `CreateProduct` you have to specify an order unit, in `UpdateProduct` you don't. That's because in `UpdateProduct` the attributes that are unspecified won't be modified, while in `CreateProduct` they are actually used to create the product.

Third, we have implemented the API in various languages. Some of them simply don't have object-oriented features like inheritance. E.g. [Go has composition but not inheritance](https://golangbot.com/inheritance/). While we try to implement a library that looks and feels good on each supported platform (e.g. Java, .NET, Go, PHP, and ABAP), it's simply too much work to do so for every single feature.

So, unfortunately, we won't refactor the library and you will need to copy & paste some fields. We hope you only have to do so a few times during the lifetime of a project. In other terms, we try very hard to keep the API stable e.g. in terms of endpoints and field names (it has changes many times behind the scenes). There wasn't a breaking change in years.

HTH

**Comment by manuelbostanci** [comment]
Hi @olivere,
thanks for the detailed answer! 
Just one more question about the *Product classes. 
I was wondering why some attributes have different types (e.g. double and Double or boolean and Boolean). Is it possible to unify these? 
In addition to that, for us it would be helpful, if the *Product classes contains .equals() methods.
Would it be possible to add them? ;) 

Thanks! ;)

**Comment by olivere** [comment]
Hmm... I'm not a Java expert, but isn't `double` a primitive type which cannot be assigned a `null` value? I'm pretty sure that sometimes a `null` is allowed and when it is, the API uses the object type, not the primitive type.

Yeah, `equals` and `hashCode` could probably be implemented for the types. Will put it in the backlog (#6).

I'm not sure if this will help you though, but of course I'm not sure what you're trying to achieve. E.g. if you're trying to fill up the product data from your source and compare it with the product you'll get with the API, `equals` will probably be `false`. The reason is that there might be fields that are set _after_ being imported by your code, e.g. we sometimes need to fix the tax code/tax rate. And if you'll compare them naively, you will always get a value of `false`.

**Comment by manuelbostanci** [comment]
Thanks for the information. ;)
